name: lint

on:
  workflow_call: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    container: python:3.12

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Lint with pre-commit
      run: |
        apt-get update
        git config --global --add safe.directory '*'
        git fetch --all -q
        git switch $GITHUB_HEAD_REF
        git pull origin $GITHUB_HEAD_REF --rebase
        pip install --upgrade pre-commit
        pre-commit run --from-ref "origin/$GITHUB_BASE_REF" --to-ref "$GITHUB_HEAD_REF"
